site_name: Wiki
site_url: http://soc.shellcode.blog
theme:
  name: 'mkdocs'
  palette: 
    primary: 'black'
    accent: 'orange'
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - codehilite:
      linenums: true
nav:
  - 'Home': 'index.md'
  - 'API':
    - 'Homepage': "API/index.md"
  - 'VirusTotal':
    - 'Homepage': "VirusTotal/index.md"
  - 'Reconfigure_Proxy':
    - 'Homepage': "Reconfigure_Proxy/index.html"
  - 'AbuseIPDB':
    - 'Homepage': "AbuseIPDB/index.md"
  - 'Hybrid Analysis':
    - 'Homepage': "Hybrid_Analysis.md"
  - 'Any.Run':
    - 'Homepage': "Any_Run.md"
  - 'UrlScan.io':
    - 'Homepage': "UrlScan_io.md"
  - 'OTX AlienVault':
    - 'Homepage': "OTX_AlienVault.md"
  - 'ThreatCrowd':
    - 'Homepage': "ThreatCrowd.md"
  - 'ThreatMiner':
    - 'Homepage': "ThreatMiner.md"
  - 'Shodan':
    - 'Homepage': "Shodan.md"
  - 'Censys':
    - 'Homepage': "Censys.md"
  - 'Fortiguard':
    - 'Homepage': "Fortiguard.md"
  - 'Talos Intelligence':
    - 'Homepage': "Talos_Intelligence.md"

extra_css:
  - assets/css/custom.css
